server:
  port: ${SERVER_PORT:9000}

spring:
  web:
    resources:
      static-locations: classpath:/web/

mosaic:
  startup:
    resource-path: "[JSON]classpath:start1.json"

  plugin:
    # 推荐的配置方式
    # storage-path: /data/mosaic/plugins          # Linux/Mac
    storage-path: E:/plugins           # Windows绝对路径
    # storage-path: ./plugins                   # 相对路径
    # storage-path: ${user.home}/mosaic/plugins # 用户主目录
