server:
  port: ${SERVER_PORT:9000}

spring:
  web:
    resources:
      static-locations: classpath:/web/

mosaic:
  startup:
    resource-path: "[JSON]classpath:start1.json"
  chunk:
    bind:
      port: 8848
  persistence:
    type: json

  plugin:
    # 推荐的配置方式
    storage-path: /Users/suifeng/Code/mplugin          # Linux/Mac
    # storage-path:           # Windows绝对路径
    # storage-path: ./plugins                   # 相对路径
    # storage-path: ${user.home}/mosaic/plugins # 用户主目录

system.log.cube.p:
  outputFormat: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  retentionDays: 7
  logLevel: DEBUG
  maxFileSize: 1024
  

ai.chat.cube:
  apiEndpoint: https://api.siliconflow.cn/v1/chat/completions
  apiKey: sk-qdahitijgevlgckknvypdmyvpveyhbrjqyylmhfkvuedmfsf
  model: deepseek-ai/DeepSeek-R1
  maxTokens: 4096
  temperature: 0.7