name: Publish package to the Maven Central Repository
on:
  release:
    types: [published]  # 仅当正式发布 Release 时触发

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          echo -e "-----BEGIN PGP PRIVATE KEY BLOCK-----\n\
          lIYEaHOGTxYJKwYBBAHaRw8BAQdARUEeGhfYf5FSGYSr0DLj08/2GVjNzY9gYnQS\n\
          DRgXTNf+BwMC7rArt7ZG1z73Oo/ybN3FT0sMr/H3BwgTfJBEYLXT7Xv9SNPmqMvw\n\
          h0qUmFd0t6r7/t7nR+vI6+7mf37Pg04N6FXYQVzfCS/wP9Pa5P9wzbQpVGltZU1h\n\
          Y2hpbmVMYWIgPFRpbWVNYWNoaW5lTGFiQGdtYWlsLmNvbT6ImQQTFgoAQRYhBDqo\n\
          lVWmumcNJQJwSivYXAcINY+HBQJoc4ZPAhsDBQkFo5qABQsJCAcCAiICBhUKCQgL\n\
          AgQWAgMBAh4HAheAAAoJECvYXAcINY+HWYgBALT5kctWNG6Z6So81anAGEkgYGSV\n\
          0fu8jGRfjfKkqY2jAP4/Gsi1SlG9uRPda1Ciel0Cv+myHM24Fy1Va8IpZ46nD5yL\n\
          BGhzhk8SCisGAQQBl1UBBQEBB0AXoYx+Yzh0uLmtRrtvNoiiENMDoHJ/njHOpTKM\n\
          f1BzQAMBCAf+BwMCboZni+776Bz31tK+WYiFtevO2KtvuMVHVmn07aeKRnB5l8KO\n\
          N71p0v7ONokXz6R6uiYxBQ6JGTMrPxjqXDgfjePtk0xqkvfU3a7DAve8k4h+BBgW\n\
          CgAmFiEEOqiVVaa6Zw0lAnBKK9hcBwg1j4cFAmhzhk8CGwwFCQWjmoAACgkQK9hc\n\
          Bwg1j4dMNAEA9dq7ueNMHd38/fOnO02djYfLIO4rJVHfOil3uccwNbkA/1IDCVLN\n\
          kfv3iju+ufCJiKrjEvzdySCCP2UzF9DcHg8I\n\
          =qB9y\n\
          -----END PGP PRIVATE KEY BLOCK-----" | gpg --batch --import
          
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} clean deploy -DskipTests